### ISSUE TITLE
Latest version incompatible with opcua-asyncio and opcua-client-gui

### ISSUE THREAD

**Issue by kharmabum** [FreeOpcUa/opcua-widgets#12]
See related ticket: https://github.com/FreeOpcUa/opcua-client-gui/issues/64

**Error on connection**: 

```
uawidgets.utils - ERROR - 'SyncNode' object has no attribute 'get_attributes'')
Traceback (most recent call last):
  File "/Users/jcfoust/anaconda3/envs/opcgui_python_venv_38/lib/python3.8/site-packages/uawidgets/utils.py", line 21, in wrapper
    result = func(self, *args)
  File "/Users/jcfoust/Development/opcua-client-gui/uaclient/mainwindow.py", line 349, in connect
    self.tree_ui.set_root_node(self.uaclient.client.nodes.root)
  File "/Users/jcfoust/anaconda3/envs/opcgui_python_venv_38/lib/python3.8/site-packages/uawidgets/tree_widget.py", line 43, in set_root_node
    self.model.set_root_node(node)
  File "/Users/jcfoust/anaconda3/envs/opcgui_python_venv_38/lib/python3.8/site-packages/uawidgets/tree_widget.py", line 167, in set_root_node
    desc = self._get_node_desc(node)
  File "/Users/jcfoust/anaconda3/envs/opcgui_python_venv_38/lib/python3.8/site-packages/uawidgets/tree_widget.py", line 171, in _get_node_desc
    attrs = node.get_attributes([ua.AttributeIds.DisplayName, ua.AttributeIds.BrowseName, ua.AttributeIds.NodeId, ua.AttributeIds.NodeClass])
AttributeError: 'SyncNode' object has no attribute 'get_attributes'
```

**Comment by kharmabum** [comment]
Nevermind I see the issue was fix but opcua-client-gui is referencing an old version on its master branch.

**Comment by oroulet** [comment]
thank you for the report. There has been an issue in releae script. Everything should work now. Version should be 0,.6.0 on pip now
